# Generated by Django 4.1.1 on 2022-09-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=3445, max_length=50),
            preserve_default=False,
        ),
    ]
