# Generated by Django 4.1.1 on 2022-09-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_student_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark1', models.IntegerField(null=True)),
                ('mark2', models.IntegerField(null=True)),
                ('mark3', models.IntegerField(null=True)),
                ('student1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.student')),
            ],
        ),
    ]
