# Generated by Django 4.1.1 on 2022-09-26 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='mark1',
            new_name='Computer',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='mark2',
            new_name='English',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='mark3',
            new_name='Tamil',
        ),
    ]
