# Generated by Django 4.1.1 on 2022-10-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_rename_mark1_mark_computer_rename_mark2_mark_english_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='Computer',
            new_name='mark',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='English',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='Tamil',
        ),
        migrations.AddField(
            model_name='mark',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
