# Generated by Django 4.1.1 on 2022-10-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_mark_created_at_mark_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='create_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='modify_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
